name: darjoconnect
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.2
  shared_preferences: ^2.1.0
  image_picker: ^0.8.7
  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.1
  google_fonts: ^6.2.1
  intl: ^0.18.0
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.0
  flutter_launcher_icons: ^0.13.1

flutter_icons: # Konfigurasi launcher icons
  android: true
  ios: true
  image_path: "assets/images/app.png"

flutter_native_splash: # Konfigurasi splash screen
  color: "#FFFFFF" # Warna latar belakang splash screen
  image: assets/images/app.png # Path ke file logo splash
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
